server:
  port: 8099

spring:
  application:
    name: gateway


  cloud:
    consul:
      host: localhost
      port: 8500



zuul:
  routes:
    buytrip:
      path: /comprar/**
      url: http://localhost:8082
    buyfeedback:
      path: /status/**
      url: http://localhost:8084

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
  instance:
    lease-renewal-interval-in-seconds: 5
