server:
  port: 8084

spring:
  application:
    name: status

  rabbitmq:
    username: admin
    password: admin
    host: localhost

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        preferIpAddress: true
    stream:
      bindings:
        input:
          destination: compra
          group: buyprocess
  redis:
    host: localhost
    port: 6379

fila:
  saida: compras-aguardando
  finalizado: compras-finalizado



