server:
  port: 8082

spring:
  application:
    name: comprar

  rabbitmq:
    username: admin
    password: admin

  cloud:
    consul:
      host: localhost
      port: 8500
    stream:
      bindings:
        input:
          destination: compra
          group: buyprocess

fila:
  saida: compras-aguardando


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
  instance:
    lease-renewal-interval-in-seconds: 5



