version: '3.8'
services:
  db:
    container_name: mysql-8
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banco
#      MYSQL_USER: teste
#      MYSQL_PASSWORD: teste
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3307:3306'
    volumes:
      - './dbdata/data:/var/lib/mysql'
      - './dbdata/my.cnf:/etc/mysql/conf.d/my.cnf'
      - './dbdata/sql:/docker-entrypoint-initdb.d'

volumes:
  dbdata: